### PR TITLE
Metrics API

### PR DESCRIPTION
**Pull request by deoyani**
This branch addresses the requirements to create Metrics API endpoints to access the data distribution metrics data.
The metrics endpoints start with base path /usagemetrics and contain following sub paths
Details of API will be listed in a separate document.
1. To get the record/dataset metrics 
/recods
lists all the records/datasets in the database. 
this can be used to get sorted listed based on total size downloaded
/records/{recordid}
This endpoint provides the information related selected dataset, after accessing endpoint with given record/dataset id, it returns information related to dataset.

2. To get the file level metris
/files
This endpoint lists all the files who metrics are recorded in the database
/files/{filepath}
This endpoint gives information about specific file including number of unique users, downloads etc
3. To get repo level metrics
/
This returns monthly users, downloads for overall repository
4. To find overall unique users
/uniqueusers
This returns number of unique users.

To achieve above functionality set of controller and java classes added which include
MetricsController.java
MetricsRepository.java
MetricsRepositoryImpl.java

### CODE REVIEW

**Comment by deoyani** [comment]
@RayPlante 
Travis seems to be not working at the moment.

**Comment by deoyani** [comment]
Here are list of endpoints and expected results examples. 
1. Total repository level data: 

This endpoint returns repository level data, collected per month

http://localhost:8085/rmm/usagemetrics/repo?include=timestamp,total_size,number_users&exclude=_id

{

"RepoMetricsCount":1,

 "PageSize":0,

 "RepoMetrics":[

{ "timestamp": "Feb 2021",

 "Total_download": 49378173294,

 "Total_users": 116}]

}

2. Total dataset level data,

This endpoint provides information about particular dataset. Input parameter is unique dataset identifier. In this case dataset identifier is 

ex.ark:/88434/mds2-2154  or ex. 686BF41FF1D773D3E0532457068166DD1903

http://localhost:8085/rmm/usagemetrics/records/ark:/88434/mds2-2154?exclude=_id,ip_list

{   

"DataSetMetricsCount":1,

"PageSize":0,

"DataSetMetrics":

[

{"ediid":"ark:/88434/mds2-2154",

"first_time_logged":"2021-02-04T10:01:47.000+0000",

"last_time_logged":"2021-02-04T10:03:30.000+0000","total_size":19123946,

"Success_get":2,

"number_users":1}

]

}



3. Details about particular record (list of files)

This endpoint returns all the files under this dataset and provide individual file metrics data.

http://localhost:8085/rmm/usagemetrics/files/ark:/88434/mds2-2340?exclude=_id&include=ediid,filepath,success_get,download_size

   {  "FilesMetricsCount":3,

       "PageSize":0,

        "FilesMetrics":[

{"ediid":"ark:/88434/mds2-2340","filepath":"mds2-2340/round4-train-dataset/DATA_LICENSE.txt","success_get":6,"download_size":1289},

{"ediid":"ark:/88434/mds2-2340","filepath":"mds2-2340/round4-train-dataset/DATA_LICENSE.txt.sha256","success_get":6,"download_size":64},

{"ediid":"ark:/88434/mds2-2340","filepath":"mds2-2340/round4-train-dataset/METADATA.csv","success_get":6,"download_size":653697 }

]}

5. Total file level data, sort in descending order for maximum number of downloads

This endpoint lists all the files in the repository. This is an additional endpoint to list the files usage per repository. The endpoint can have pagination parameters as input and can also accept sorting request.

http://localhost:8085/rmm/usagemetrics/filemetrics?exclude=_id&sort.desc=success_get&include=ediid,filepath,success_get,download_size&page=2&size=5

{

"FilesMetricsCount":1695,

"PageSize":5,

"FilesMetrics": [{"ediid":"ark:/88434/mds2-2340","filepath":"mds2-2340/round4-train-dataset/METADATA.csv.sha256","success_get":6,"download_size":64},

{"ediid":"ark:/88434/mds2-2340","filepath":"mds2-2340/round4-train-dataset/METADATA.csv","success_get":6,"download_size":653697},

{"ediid":"ark:/88434/mds2-2340","filepath":"mds2-2340/round4-train-dataset/DATA_LICENSE.txt.sha256","success_get":6,"download_size":64},

{"ediid":"mds2-2124","filepath":"mds2-2124/NBS_Tables%20Library_with_ErratumValues.xlsx","success_get":6,"download_size":1056567},

{"ediid":"mds2-2154","filepath":"mds2-2154/SRD%2046%20Manual.pdf","success_get":6,"download_size":317423}]}



6. Individual file information (Additional endpoint might be useful in future)

I

http://localhost:8085/rmm/usagemetrics/files/686BF41FF1D773D3E0532457068166DD1903/200m.Indy.v3.2.totals.local.csv?exclude=_id,ip_list

{   "FilesMetricsCount":1,

     "PageSize":0,

     "FilesMetrics":

[{"ediid":"686BF41FF1D773D3E0532457068166DD1903","filepath":"686BF41FF1D773D3E0532457068166DD1903/200m.Indy.v3.2.totals.local.csv","success_head":0,"failure_head":0,"success_get":3,"failure_get":5,"request_id":0,"timestamp":"2021-02-09T05:03:15.000+0000","download_size":6890,"number_users":4}]

}



7. Total repository users (This endpoint lists repository level unique users)

In the following query ip_get is excluded because the ip_get contains a binary code. It represents masked ip addresses.

http://localhost:8085/rmm/usagemetrics/totalusers?exclude=_id,ip_get

{

“TotalUsersCount”: 2,

“PageSize”: 0,

“TotalUsres”: [ {},{}].  

}

**Comment by RayPlante** [comment]
Please remove  LOG_PATH_IS_UNDEFINED/rmmapp.log (and any other extraneous files).

**Review by RayPlante — CHANGES_REQUESTED** [review]
This was tested via oar-docker's update-metrics branch and functionality was fine. 

Please correct spelling error on collection name: "TotalUsres" => "TotalUsers".

**Review by RayPlante — APPROVED** [review]

**Pull request merged**
