### PR TITLE
Odd advanced search

### PR DESCRIPTION
**Pull request by deoyani**
This branch deals with many changes with respect to advanced search capability.
Mainly:
1. Syntax rules restrictions and behavior
2. Error Handling
3. key-value pairs and logical operators queries parsing and updated according to mongodb syntax
4. Free text search limitations based on MongoDB $text query limitations

### CODE REVIEW

**Comment by RayPlante** [comment]
@deoyani :  One oddity I noticed is when I looked at the API response to this query
```
https://localhost/rmm/records?searchphrase=analytical%20chemistry&title=chemistry&logicalOp=OR&title=tutorials
```
When I ran this locally under oar-docker, the response has the property `ResultCount` set to 6; however, only 3 records appear under `ResultData`.  When I run this on oardev, `ResultCount` set to 8; however, only 4 records are returned.  Is this expected?

**Comment by RayPlante** [comment]
PS: If I remove the `&logicalOp=OR&title=tutorials` in the above query, the `ResultCount` property is accurately set to 3.

**Comment by deoyani** [comment]
@RayPlante 

> PS: If I remove the `&logicalOp=OR&title=tutorials` in the above query, the `ResultCount` property is accurately set to 3.

You are right about this issue. It was indeed due to some residue code where I was making changes before confirmed some restrictions on query syntax etc. I updated code along with indentation fixes.

**Review by RayPlante — APPROVED** [review]
This PR has been tested extensively by the team via oardev, and it appears we have met the goal of consistent support for a search syntax.  Review process has successfully addressed found issues along the way.

**Pull request merged**
